package common.enums;

public enum StateType {
    OPERATIONAL_CARS_GREEN_NO_PED,
    OPERATIONAL_CARS_GREEN_PED_WAIT,
    OPERATIONAL_CARS_GREEN_INT,
    OPERATIONAL_CARS_YELLOW,
    OPERATIONAL_PEDS_WALK,
    OPERATIONAL_PEDS_FLASH,
    OFFLINE_FLASH_ON,
    OFFLINE_FLASH_OFF;
}
